# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
# Will not trigger unless PR is ready for review.

name: msal-react E2E Tests

on:
    pull_request:
        types: [opened, reopened, synchronize, ready_for_review]
        paths:
            - "lib/msal-react/**/*"
            - "lib/msal-browser/**/*"
            - "lib/msal-common/**/*"
            - "samples/msal-react-samples/**/*"
            - "samples/e2eTestUtils/**/*"
            - "samples/package-lock.json"
            - "!**.md"
            - ".github/workflows/msal-react-e2e.yml"
    merge_group:
        types: [checks_requested]

concurrency:
    group: react-e2e-${{github.ref}}
    cancel-in-progress: true

permissions:
    contents: read

jobs:
    run-e2e:
        if: (github.repository == 'AzureAD/microsoft-authentication-library-for-js') && (github.actor != 'dependabot[bot]') && ((github.event.pull_request.head.repo.full_name == github.repository) || (github.event_name == 'merge_group')) && !github.event.pull_request.draft
        runs-on: ubuntu-latest

        strategy:
            fail-fast: false
            matrix:
                sample:
                    - "react-router-sample"
                    - "nextjs-sample"
                    - "gatsby-sample"
                    - "typescript-sample"
                    - "b2c-sample"

        name: ${{ matrix.sample }}

        steps:
            - uses: actions/checkout@v4

            - name: Use Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 20
                  cache: "npm"

            - name: Clean Install
              run: npm ci --workspace=samples/msal-react-samples/${{matrix.sample}}

            # Required because of https://github.com/npm/cli/issues/4828
            - name: React optional dependencies
              run: npm install --workspace=samples/msal-react-samples/${{matrix.sample}} --no-save @rollup/rollup-linux-x64-gnu @parcel/watcher-linux-x64-glibc

            - name: Build packages
              working-directory: lib/msal-react
              run: npm run build:all

            - name: Build ${{ matrix.sample }}
              working-directory: samples/msal-react-samples/${{ matrix.sample }}
              run: npm run build

            - name: E2E Tests
              working-directory: samples/msal-react-samples/${{ matrix.sample }}
              timeout-minutes: 5
              env:
                  AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
                  AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
                  AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
              run: npm test

            - name: Upload E2E Test Screenshots
              uses: actions/upload-artifact@v4
              if: failure()
              with:
                  name: e2e-test-screenshots
                  path: samples/**/screenshots
